django_bookmarks/urls.py
# The file imports everything from the module django.conf.urls.defaults.
# This module provides the necessary functions to define URLs.
import os.path
from django.conf.urls import *
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

# We import everything from bookmarks.views.
# This is necessary to access our views, and connect them to URLs.
from bookmarks import *
from bookmarks.views import *


site_media = os.path.join(
    os.path.dirname(__file__), 'site_media'
)

urlpatterns = [
    #Browsing
    url(r'^$', main_page),
    url(r'^tag/([^\s]+)/$', tag_page),
    url(r'^user/(\w+)/$', user_page),
    url(r'^tag/$', tag_cloud_page),
    url(r'^search/$', search_page),

    #Session management
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', logout_page),
    url(r'^site_media/(?P<path>.*)$', serve, { 'document_root': site_media }),
    url(r'^register/$', register_page),
    url(r'^register/success/$', TemplateView.as_view(template_name='registration/register_success.html')),

    #Account management
    url(r'^save/$', bookmark_save_page),
]

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Link(models.Model):
    url = models.URLField(unique=True)

    def __str__(self):
        return self.url

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __str__(self):
        return '%s, %s' % (self.user.username, self.link.url)

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)

    def __str__(self):
        return self.name

django_bookmarks/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Bookmarks |
        {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/site_media/style.css"
        type="text/css" />
    <script type="text/javascript" src="/site_media/jquery.js"></script>
    {% block external %}{% endblock %}
</head>
<body>
    <div id="nav">
        <a href="/">Home</a> |
        {% if user.is_authenticated %}
            <a href="/save/">Submit</a> |
            <a href="/search/">Search</a> |
            <a href="/user/{{ user.username }}/">
                {{ user.username }}</a> |
            <a href="/logout/">Logout</a>
        {% else %}
            <a href="/login/">Login</a> |
            <a href="/register/">Register</a>
        {% endif %}
    </div>
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

django_bookmarks/templates/bookmark_list.html
{% if bookmarks %}
    <ul class="bookmarks">
        {% for bookmark in bookmarks %}
            <li>
                <a href="{{ bookmark.link.url|escape }}" class="title">
                    {{ bookmark.title|escape }}</a>
                {% if show_edit %}
                    <a href="/save/?url={{ bookmark.link.url|urlencode }}"
                        class="edit">[edit]</a>
                {% endif %}
                <br />
                {% if show_tags %}
                    Tags:
                    {% if bookmark.tag_set.all %}
                        <ul class="tags">
                            {% for tag in bookmark.tag_set.all %}
                                <li>
                                    <a href="/tag/{{ tag.name|urlencode }}/">{{ tag.name|escape }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        None.
                    {% endif %}
                    <br />
                {% endif %}
                {% if show_user %}
                    Posted by:
                    <a href="/user/{{ bookmark.user.username }}/"
                    class="username">
                        {{ bookmark.user.username }}</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

django_bookmarks/templates/bookmark_save.html
{% extends "base.html" %}
{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

django_bookmarks/templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block content %}
    {% if user.username %}
        <p>Welcome {{ user.username }}!
            Here you can store and share bookmarks!</p>
    {% else %}
        <p>Welcome anonymous user!
            You need to <a href="/login/">login</a>
            before you can store and share bookmarks.</p>
    {% endif %}
{% endblock %}

django_bookmarks/templates/search.html
{% extends "base.html" %}
{% block external %}
    <script type="text/javascript" src="/site_media/search.js"></script>
{% endblock %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks {% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
    {{ form.as_p }}
    <input type="submit" value="search" />
</form>
<div id="search-results">
    {% if show_results %}
        {% include 'bookmark_list.html' %}
    {% endif %}
</div>
{% endblock %}

django_bookmarks/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block content %}
    <div id="tag-cloud">
        {% for tag in tags %}
            <a href="/tag/{{ tag.name|urlencode }}/"
            class="tag-cloud-{{ tag.weight }}">
                {{ tag.name|escape }}</a>
        {% endfor %}
    </div>
{% endblock %}

django_bookmarks/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name|escape }}{% endblock %}
{% block head %}
    Bookmarks for tag: {{ tag_name|escape }}{% endblock %}
{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}

django_bookmarks/templates/user_page.html
{% extends "base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}
{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}